<?php

namespace Database\Seeders;

use App\Models\Club;
use App\Models\District;
use App\Models\User;
use Illuminate\Database\Seeder;

class PlayerDistrictSeeder extends Seeder
{
    /**
     * Maps club names (from Profixio) to their district federation.
     */
    private array $clubDistrictMap = [
        'Aga BTK' => 'Västergötlands Bordtennisförbund',
        'Alfta BTK' => 'Hälsinglands Bordtennisförbund',
        'Alby IF' => 'Stockholms Bordtennisförbund',
        'Alingsås PK' => 'Göteborgs Bordtennisförbund',
        'Arboga BTK' => 'Södermanlands Bordtennisförbund',
        'Arkelstorps BTK' => 'Blekinge Bordtennisförbund',
        'Arvika BTK' => 'Värmlands Bordtennisförbund',
        'Asige BTK' => 'Hallands Bordtennisförbund',
        'Askims BTK' => 'Göteborgs Bordtennisförbund',
        'Ås IF' => 'Göteborgs Bordtennisförbund',
        'Åsa IF' => 'Hallands Bordtennisförbund',
        'Åstorps BTK' => 'Skånes Bordtennisförbund',
        'Åtvidabergs TK' => 'Östergötlands BTF',
        'Ålsta BTK' => 'Medelpads Bordtennisförbund',
        'Back BTK' => 'Göteborgs Bordtennisförbund',
        'Backa BTK' => 'Göteborgs Bordtennisförbund',
        'Barva IF' => 'Smålands Bordtennisförbund',
        'Bergkvara BTK' => 'Smålands Bordtennisförbund',
        'Bjärreds BTK' => 'Skånes Bordtennisförbund',
        'Bjärnums BTK' => 'Skånes Bordtennisförbund',
        'Björkborns GOIF' => 'Örebro Läns Bordtennisförbund',
        'Blikstorps AIK' => 'Västergötlands Bordtennisförbund',
        'Bohus IF' => 'Bohuslän-Dals BTF',
        'Borgstena IF' => 'Västergötlands Bordtennisförbund',
        'Borlänge BTK' => 'Dalarnas Bordtennisförbund',
        'Bortans IK' => 'Smålands Bordtennisförbund',
        'Boo Racketklubb' => 'Stockholms Bordtennisförbund',
        'Breviks SK' => 'Bohuslän-Dals BTF',
        'Bromölla BTK' => 'Skånes Bordtennisförbund',
        'Bro IK' => 'Stockholms Bordtennisförbund',
        'Bruzaholms SK' => 'Smålands Bordtennisförbund',
        'BTK Ajax/ Österlen' => 'Skånes Bordtennisförbund',
        'BTK Arsenal Nybro' => 'Smålands Bordtennisförbund',
        'BTK Clipper' => 'Östergötlands BTF',
        'BTK Dalen' => 'Stockholms Bordtennisförbund',
        'BTK Enig' => 'Örebro Läns Bordtennisförbund',
        'BTK Final' => 'Västergötlands Bordtennisförbund',
        'BTK Frej' => 'Stockholms Bordtennisförbund',
        'BTK Kälom' => 'Medelpads Bordtennisförbund',
        'BTK Kävlinge' => 'Skånes Bordtennisförbund',
        'BTK Kungsör' => 'Södermanlands Bordtennisförbund',
        'BTK Linné' => 'Göteborgs Bordtennisförbund',
        'BTK Näcken' => 'Stockholms Bordtennisförbund',
        'BTK Ratic' => 'Göteborgs Bordtennisförbund',
        'BTK Rekord' => 'Örebro Läns Bordtennisförbund',
        'BTK Safir' => 'Stockholms Bordtennisförbund',
        'BTK Scania' => 'Skånes Bordtennisförbund',
        'BTK Warta' => 'Stockholms Bordtennisförbund',
        'BTK-72 Trönninge' => 'Hallands Bordtennisförbund',
        'BTK Örebro Väster' => 'Örebro Läns Bordtennisförbund',
        'BTK Åsen' => 'Ångermanlands Bordtennisförbund',
        'Bullarens GoIF' => 'Bohuslän-Dals BTF',
        'Bålsta BTK' => 'Nordöstra Svealands Bordtennisförbund',
        'Bärke Bordtennisklubb' => 'Dalarnas Bordtennisförbund',
        'Byttorps IF' => 'Västergötlands Bordtennisförbund',
        'Böksholms IF' => 'Smålands Bordtennisförbund',
        'Bälinge IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Carlshamns BTK' => 'Blekinge Bordtennisförbund',
        'Carlstads BTK' => 'Värmlands Bordtennisförbund',
        'Dala-Järna IK' => 'Dalarnas Bordtennisförbund',
        'Dagsbergs IF' => 'Östergötlands BTF',
        'Damsnäs IF' => 'Norrlands Bordtennisförbund',
        'Degeberga GOIF' => 'Skånes Bordtennisförbund',
        'Djurgårdens IF BTF' => 'Stockholms Bordtennisförbund',
        'Docksta BTK' => 'Ångermanlands Bordtennisförbund',
        'Dänningelanda BTK' => 'Smålands Bordtennisförbund',
        'Eds FF' => 'Nordöstra Svealands Bordtennisförbund',
        'Ekerö IK' => 'Stockholms Bordtennisförbund',
        'Ekeby IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Enköpings Pingisveteraner' => 'Nordöstra Svealands Bordtennisförbund',
        'Ervalla SK' => 'Örebro Läns Bordtennisförbund',
        'Eskilstuna BTK' => 'Södermanlands Bordtennisförbund',
        'Eslövs AI BTK' => 'Skånes Bordtennisförbund',
        'Essunga Södra BTK' => 'Västergötlands Bordtennisförbund',
        'Fagersta Södra IK' => 'Västmanlands Bordtennisförbund',
        'Faggemåla BTK' => 'Smålands Bordtennisförbund',
        'Falkenbergs BTK' => 'Hallands Bordtennisförbund',
        'Fårösunds GOIK' => 'Gotlands Bordtennisförbund',
        'Fältöverstens BTK' => 'Stockholms Bordtennisförbund',
        'Färila BTK' => 'Hälsinglands Bordtennisförbund',
        'FIFH Malmö' => 'Skånes Bordtennisförbund',
        'Flens BTK' => 'Södermanlands Bordtennisförbund',
        'Fole IF' => 'Gotlands Bordtennisförbund',
        'Föreningen Kärrtorps Pingisakademi' => 'Stockholms Bordtennisförbund',
        'Gagnefs IF' => 'Dalarnas Bordtennisförbund',
        'Gammalstorps GOIF' => 'Blekinge Bordtennisförbund',
        'Gefle PK' => 'Gästriklands Bordtennisförbund',
        'Gistad SMK' => 'Östergötlands BTF',
        'Grästorps BTK' => 'Västergötlands Bordtennisförbund',
        'Gropens IF' => 'Västergötlands Bordtennisförbund',
        'Grundsunds IF' => 'Bohuslän-Dals BTF',
        'Gullabo SK' => 'Smålands Bordtennisförbund',
        'Gävle Handikappades IF' => 'Gästriklands Bordtennisförbund',
        'Haga FF' => 'Stockholms Bordtennisförbund',
        'Hagenberg Åmåls västra BoIF' => 'Bohuslän-Dals BTF',
        'Hagenberg Åmåls västra Bygdegårds- och Idrottsföre' => 'Bohuslän-Dals BTF',
        'Hallstahammars BTK' => 'Västmanlands Bordtennisförbund',
        'Halmstad BTK' => 'Hallands Bordtennisförbund',
        'Hammarby IF BTF' => 'Stockholms Bordtennisförbund',
        'Hangelösa IF' => 'Västergötlands Bordtennisförbund',
        'Haparanda SKT' => 'Norrbottens Bordtennisförbund',
        'Heby AIF' => 'Nordöstra Svealands Bordtennisförbund',
        'Herrljunga BTK' => 'Västergötlands Bordtennisförbund',
        'Horreds BTK' => 'Västergötlands Bordtennisförbund',
        'Hova BTK' => 'Västergötlands Bordtennisförbund',
        'Hudiksvalls IF BTK' => 'Hälsinglands Bordtennisförbund',
        'Huddinge BTK' => 'Stockholms Bordtennisförbund',
        'Huskvarna Södra IS' => 'Smålands Bordtennisförbund',
        'Håcksviks IF' => 'Västergötlands Bordtennisförbund',
        'Hyssna BTK' => 'Västergötlands Bordtennisförbund',
        'Hylta GF' => 'Hallands Bordtennisförbund',
        'Höga Kusten AIF' => 'Ångermanlands Bordtennisförbund',
        'Höökens BTK' => 'Smålands Bordtennisförbund',
        'Hörby BIK' => 'Skånes Bordtennisförbund',
        'Hälleforsnäs Bordtennisklubb' => 'Södermanlands Bordtennisförbund',
        'Hässelby Pensionärers BTK' => 'Stockholms Bordtennisförbund',
        'Hässleholms Bordtennisklubb' => 'Skånes Bordtennisförbund',
        'Hålta IK' => 'Bohuslän-Dals BTF',
        'Härnösands Racketklubb' => 'Ångermanlands Bordtennisförbund',
        'IF Ale' => 'Göteborgs Bordtennisförbund',
        'IF Hansa-Hoburg' => 'Gotlands Bordtennisförbund',
        'IF Ifo' => 'Blekinge Bordtennisförbund',
        'IF Norcopensarna' => 'Stockholms Bordtennisförbund',
        'IFA Eskilstuna' => 'Södermanlands Bordtennisförbund',
        'IFAH Parasport' => 'Stockholms Bordtennisförbund',
        'IFK Falköping BTK' => 'Västergötlands Bordtennisförbund',
        'IFK Haninge' => 'Stockholms Bordtennisförbund',
        'IFK Klagshamn' => 'Skånes Bordtennisförbund',
        'IFK Lidingös BTK' => 'Stockholms Bordtennisförbund',
        'IFK Lidköping' => 'Västergötlands Bordtennisförbund',
        'IFK Lund Bordtennis' => 'Skånes Bordtennisförbund',
        'IFK Mariefred' => 'Södermanlands Bordtennisförbund',
        'IFK Österåkers BTK' => 'Stockholms Bordtennisförbund',
        'IFK Täby BTK' => 'Stockholms Bordtennisförbund',
        'IFK Visby' => 'Gotlands Bordtennisförbund',
        'IK Juno' => 'Östergötlands BTF',
        'IK Makkabi' => 'Stockholms Bordtennisförbund',
        'IK Sirius BTK' => 'Nordöstra Svealands Bordtennisförbund',
        'IK Sjöge' => 'Östergötlands BTF',
        'Iggesunds BTK' => 'Hälsinglands Bordtennisförbund',
        'Ingarö IF' => 'Stockholms Bordtennisförbund',
        'Istrums SK' => 'Västergötlands Bordtennisförbund',
        'Jarlabergs BTK' => 'Södermanlands Bordtennisförbund',
        'Järfälla BTF' => 'Stockholms Bordtennisförbund',
        'Järna SK' => 'Södermanlands Bordtennisförbund',
        'Jämjö BTK' => 'Blekinge Bordtennisförbund',
        'Jägarnäs-Ludvika BTK' => 'Dalarnas Bordtennisförbund',
        'Kalmar BTK' => 'Sydöstra Götalands BTF',
        'Karlsborgs BTK' => 'Västergötlands Bordtennisförbund',
        'Katrineholms BTK' => 'Södermanlands Bordtennisförbund',
        'Kebnekaise BTK' => 'Norrbottens Bordtennisförbund',
        'KFUM Gävle BT' => 'Gästriklands Bordtennisförbund',
        'KFUM Jönköping IA' => 'Smålands Bordtennisförbund',
        'KFUM Kristianstad BTF' => 'Skånes Bordtennisförbund',
        'KFUM Stocksund IA' => 'Stockholms Bordtennisförbund',
        'Kils Bordtennisklubb' => 'Värmlands Bordtennisförbund',
        'Kinna BTK' => 'Västergötlands Bordtennisförbund',
        'Klintehamns IK' => 'Gotlands Bordtennisförbund',
        'Klippans BTK' => 'Skånes Bordtennisförbund',
        'Kosta SK' => 'Smålands Bordtennisförbund',
        'Kristinehamns BTF' => 'Värmlands Bordtennisförbund',
        'Kristvalla BTK' => 'Sydöstra Götalands BTF',
        'Kuddby IF' => 'Östergötlands BTF',
        'Kullåkra BTK' => 'Skånes Bordtennisförbund',
        'Kungsgårdens IS' => 'Nordöstra Svealands Bordtennisförbund',
        'Kungälvs BTK' => 'Bohuslän-Dals BTF',
        'Kungsbacka BTK' => 'Hallands Bordtennisförbund',
        'Kvarnby AK' => 'Skånes Bordtennisförbund',
        'Kvillebyns SK' => 'Bohuslän-Dals BTF',
        'Kyrkhults BTK' => 'Blekinge Bordtennisförbund',
        'Kållekärrs IK' => 'Bohuslän-Dals BTF',
        'Kågeröds BTK' => 'Skånes Bordtennisförbund',
        'Kättilsmåla BTK' => 'Sydöstra Götalands BTF',
        'Laholms BTK Serve' => 'Hallands Bordtennisförbund',
        'Larvs FK' => 'Västergötlands Bordtennisförbund',
        'Lessebo BTK' => 'Sydöstra Götalands BTF',
        'Levide IF' => 'Gotlands Bordtennisförbund',
        'Lidan BTK' => 'Västergötlands Bordtennisförbund',
        'Lilla Alby SK' => 'Stockholms Bordtennisförbund',
        'Limhamns BTK' => 'Skånes Bordtennisförbund',
        'Linden BTK Eskilstuna' => 'Södermanlands Bordtennisförbund',
        'Linköpings Parasportförening' => 'Östergötlands BTF',
        'Linköpings Pingisklubb' => 'Östergötlands BTF',
        'LinnePartille PK' => 'Göteborgs Bordtennisförbund',
        'Listerby IK' => 'Blekinge Bordtennisförbund',
        'Ljungby BTK' => 'Smålands Bordtennisförbund',
        'Ljungsbro BTK' => 'Östergötlands BTF',
        'Luleå PF' => 'Norrbottens Bordtennisförbund',
        'Lyckeby BTK' => 'Blekinge Bordtennisförbund',
        'Långemåla BTK' => 'Sydöstra Götalands BTF',
        'Långshyttans BTK' => 'Dalarnas Bordtennisförbund',
        'Malmbergets AIF' => 'Norrbottens Bordtennisförbund',
        'Malmö IF' => 'Skånes Bordtennisförbund',
        'Mariedals IK' => 'Västergötlands Bordtennisförbund',
        'Marma IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Mariestads BTK' => 'Västergötlands Bordtennisförbund',
        'Markaryds BTK' => 'Smålands Bordtennisförbund',
        'MK Veteranen' => 'Stockholms Bordtennisförbund',
        'Molkoms Racketklubb' => 'Värmlands Bordtennisförbund',
        'Munkfors BTK' => 'Värmlands Bordtennisförbund',
        'Munkedals BTK' => 'Bohuslän-Dals BTF',
        'Mölndals BTK' => 'Göteborgs Bordtennisförbund',
        'Mörrums GOIS BTK' => 'Blekinge Bordtennisförbund',
        'Nerikes Kils SK' => 'Örebro Läns Bordtennisförbund',
        'Nickebo IK' => 'Södermanlands Bordtennisförbund',
        'Nora LTK' => 'Örebro Läns Bordtennisförbund',
        'Norra BTK' => 'Västerbottens Bordtennisförbund',
        'Norrfjärns IF' => 'Medelpads Bordtennisförbund',
        'Norrtulls SK' => 'Stockholms Bordtennisförbund',
        'Norrtälje BTK' => 'Stockholms Bordtennisförbund',
        'Nynäshamns BTK' => 'Stockholms Bordtennisförbund',
        'Nävragöls BK' => 'Sydöstra Götalands BTF',
        'Nyköpings Oxelösund BTK' => 'Södermanlands Bordtennisförbund',
        'Ortvikens PK' => 'Medelpads Bordtennisförbund',
        'Oskarshamns BTK' => 'Sydöstra Götalands BTF',
        'Ovansiljans Sportklubb' => 'Dalarnas Bordtennisförbund',
        'Pensionärernas BTK' => 'Stockholms Bordtennisförbund',
        'PitePingis BTF' => 'Norrbottens Bordtennisförbund',
        'PK Sundsvall' => 'Medelpads Bordtennisförbund',
        'Rimbo IF' => 'Stockholms Bordtennisförbund',
        'Romelanda UF' => 'Bohuslän-Dals BTF',
        'Rotebro BTK' => 'Stockholms Bordtennisförbund',
        'Rudalens IF' => 'Ångermanlands Bordtennisförbund',
        'Rydöbruks IF' => 'Blekinge Bordtennisförbund',
        'Röke Förening Sport Förening' => 'Skånes Bordtennisförbund',
        'Sandsjöfors SK' => 'Smålands Bordtennisförbund',
        'Sandvikens BTK' => 'Gästriklands Bordtennisförbund',
        'Sandareds BTK' => 'Västergötlands Bordtennisförbund',
        'Särö Kullavik Idrottsförening' => 'Hallands Bordtennisförbund',
        'Sävast BTK Boden' => 'Norrbottens Bordtennisförbund',
        'Sävsjö BTK' => 'Smålands Bordtennisförbund',
        'Senorens IF' => 'Ångermanlands Bordtennisförbund',
        'SF Sindjelic' => 'Stockholms Bordtennisförbund',
        'Sibbarps GOIF' => 'Skånes Bordtennisförbund',
        'Sicklasjöns Bollklubb' => 'Stockholms Bordtennisförbund',
        'Sigtuna IF BTK' => 'Nordöstra Svealands Bordtennisförbund',
        'Simlångsdalens IF' => 'Hallands Bordtennisförbund',
        'Sjöbo BTK' => 'Skånes Bordtennisförbund',
        'Sjömarkens BTK' => 'Västergötlands Bordtennisförbund',
        'Skagersviks BTK' => 'Bohuslän-Dals BTF',
        'Skee IF' => 'Bohuslän-Dals BTF',
        'Skellefteå AIK BTF' => 'Västerbottens Bordtennisförbund',
        'Skedala BTK' => 'Hallands Bordtennisförbund',
        'SK Frigg' => 'Nordöstra Svealands Bordtennisförbund',
        'SK Hakoah' => 'Stockholms Bordtennisförbund',
        'Skoghalls BTK' => 'Värmlands Bordtennisförbund',
        'Skurups BTK' => 'Skånes Bordtennisförbund',
        'Skuttunge SK' => 'Nordöstra Svealands Bordtennisförbund',
        'Skövde PK' => 'Västergötlands Bordtennisförbund',
        'Skyttorps IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Sollefteå BTK' => 'Ångermanlands Bordtennisförbund',
        'Solna BTK' => 'Stockholms Bordtennisförbund',
        'Spånga TBK' => 'Stockholms Bordtennisförbund',
        'Spårvägens BTK' => 'Stockholms Bordtennisförbund',
        'Spårvägens Veteran BTK' => 'Stockholms Bordtennisförbund',
        'Staffanstorps BTK' => 'Skånes Bordtennisförbund',
        'Stenungsunds BTF' => 'Bohuslän-Dals BTF',
        'Stjärnhovs IK' => 'Södermanlands Bordtennisförbund',
        'Stockholms-Postens IK' => 'Stockholms Bordtennisförbund',
        'Storå BTK' => 'Örebro Läns Bordtennisförbund',
        'Storfors BTK' => 'Värmlands Bordtennisförbund',
        'Storumans IK' => 'Västerbottens Bordtennisförbund',
        'Storvreta IK' => 'Nordöstra Svealands Bordtennisförbund',
        'Strängnäs BTK' => 'Södermanlands Bordtennisförbund',
        'Stratos Enköping BTK' => 'Nordöstra Svealands Bordtennisförbund',
        'Strömsunds BTK' => 'Jämtland-Härjedalens Bordtennisförbund',
        'Strövelstorp BTK' => 'Skånes Bordtennisförbund',
        'Sunnersta AIF' => 'Nordöstra Svealands Bordtennisförbund',
        'Sundbybergs IK' => 'Stockholms Bordtennisförbund',
        'Svanesunds GIF' => 'Bohuslän-Dals BTF',
        'Svedbergs GIF' => 'Västergötlands Bordtennisförbund',
        'Söderhamns UIF' => 'Hälsinglands Bordtennisförbund',
        'Södertälje BTK' => 'Stockholms Bordtennisförbund',
        'Södra Vi IF' => 'Östergötlands BTF',
        'Sölvesborgs BTK' => 'Blekinge Bordtennisförbund',
        'Tabergs SK' => 'Smålands Bordtennisförbund',
        'Tibble-Kungsängen BTK' => 'Stockholms Bordtennisförbund',
        'Tomelilla AIS' => 'Skånes Bordtennisförbund',
        'TopSpeed BTK' => 'Stockholms Bordtennisförbund',
        'Torslanda Bordtennisklubb' => 'Göteborgs Bordtennisförbund',
        'Torslanda IK' => 'Göteborgs Bordtennisförbund',
        'Tranås BTK' => 'Smålands Bordtennisförbund',
        'Trelleborgs BTK' => 'Skånes Bordtennisförbund',
        'Trosa RK' => 'Södermanlands Bordtennisförbund',
        'Trollhättans BTK' => 'Nordvästra Götalands Bordtennisförbund',
        'Tullinge TP BTK' => 'Stockholms Bordtennisförbund',
        'Töreboda BTK' => 'Västergötlands Bordtennisförbund',
        'Tyresö BTK' => 'Stockholms Bordtennisförbund',
        'Tärnsjö BTK' => 'Nordöstra Svealands Bordtennisförbund',
        'Uddevalla BTK' => 'Bohuslän-Dals BTF',
        'Ulricehamns IF' => 'Västergötlands Bordtennisförbund',
        'Umedalens IF' => 'Västerbottens Bordtennisförbund',
        'Umeå BTK' => 'Västerbottens Bordtennisförbund',
        'Upplands Väsby BTK' => 'Stockholms Bordtennisförbund',
        'Upplands-Ekeby IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Uppsala Life IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Vadsbro IF' => 'Södermanlands Bordtennisförbund',
        'Vadstena BTK' => 'Östergötlands BTF',
        'Vallentuna BTK' => 'Stockholms Bordtennisförbund',
        'Valdemarsviks IF' => 'Östergötlands BTF',
        'Vara SK' => 'Västergötlands Bordtennisförbund',
        'Varekils IF' => 'Bohuslän-Dals BTF',
        'Varbergs BTK' => 'Hallands Bordtennisförbund',
        'Varnhems IF' => 'Västergötlands Bordtennisförbund',
        'Vassunda IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Vedums AIS' => 'Västergötlands Bordtennisförbund',
        'Vellinge Näsets Bordtennisklubb' => 'Skånes Bordtennisförbund',
        'Verums GOIF' => 'Skånes Bordtennisförbund',
        'Vetlanda BTK' => 'Smålands Bordtennisförbund',
        'Vikarby IK' => 'Dalarnas Bordtennisförbund',
        'Vindelns IF' => 'Västerbottens Bordtennisförbund',
        'Visby BTK' => 'Gotlands Bordtennisförbund',
        'Visby IF Gute BTK' => 'Gotlands Bordtennisförbund',
        'Vällingby BTK Pensionärer' => 'Stockholms Bordtennisförbund',
        'Värmskogs SK' => 'Värmlands Bordtennisförbund',
        'Värnamo TK' => 'Smålands Bordtennisförbund',
        'Västerås BTK' => 'Västmanlands Bordtennisförbund',
        'Västers BTK' => 'Västmanlands Bordtennisförbund',
        'Vänersborgs BTK' => 'Nordvästra Götalands Bordtennisförbund',
        'Vaggeryds BTK' => 'Smålands Bordtennisförbund',
        'Ängby SK' => 'Stockholms Bordtennisförbund',
        'Östergarns IK' => 'Gotlands Bordtennisförbund',
        'Östansjö IF' => 'Gästriklands Bordtennisförbund',
        'Östersunds GIF' => 'Jämtland-Härjedalens Bordtennisförbund',
        'Östhammars SK' => 'Nordöstra Svealands Bordtennisförbund',
        'Öckerö IF' => 'Bohuslän-Dals BTF',
        'Ödenäs IF' => 'Västergötlands Bordtennisförbund',
        'Örebro Bordtennis Seniorer' => 'Örebro Läns Bordtennisförbund',
        'Öregrunds IK' => 'Nordöstra Svealands Bordtennisförbund',
        'Örbyhus IF' => 'Nordöstra Svealands Bordtennisförbund',
        'Örjansklubben/Ramkvilla IF' => 'Smålands Bordtennisförbund',
        'Örslösa-Söne IK' => 'Västergötlands Bordtennisförbund',
        'Öråns SK' => 'Blekinge Bordtennisförbund',
        'Östra Stadsgränsen TK' => 'Stockholms Bordtennisförbund',
        'Ölmstad IS' => 'Östergötlands BTF',
        'Överlida IK' => 'Västergötlands Bordtennisförbund',
    ];

    public function run(): void
    {
        // Step 1: Collect unique district names and upsert them.
        // profixio_id is required (non-nullable) but we don't have real IDs from
        // the PDF, so we use a high offset (9000+) to avoid clashing with scraped data.
        $uniqueDistricts = array_unique(array_values($this->clubDistrictMap));
        sort($uniqueDistricts);

        $districtIndex = 9000;
        foreach ($uniqueDistricts as $districtName) {
            District::firstOrCreate(
                ['name' => $districtName],
                ['profixio_id' => $districtIndex++]
            );
        }

        $this->command->info('Districts upserted: ' . \count($uniqueDistricts));

        // Step 2: For each club→district entry, find matching users and set district_id.
        $updated = 0;
        $skipped = 0;

        foreach ($this->clubDistrictMap as $clubName => $districtName) {
            $club = Club::where('name', $clubName)->first();

            if (! $club) {
                $skipped++;
                continue;
            }

            $district = District::where('name', $districtName)->first();

            if (! $district) {
                $skipped++;
                continue;
            }

            $count = User::where('club_id', $club->id)
                ->update(['district_id' => $district->id]);

            $updated += $count;
        }

        $this->command->info("Players updated with district: {$updated}");
        $this->command->warn("Clubs not found in DB (skipped): {$skipped}");
    }
}
